### ISSUE TITLE
Gallery for Sports and Parties, various problems

### ISSUE THREAD

**Issue by filibert0** [SnowdaysIT/snowdays-front-end#16]
This happens on currently online version of snowdays.it, chrome on windows, screen resolution 1920*1080

With Sports selected, Using chrome on windows with a window around 900px wide, this happens. With a larger or smaller window it's fine.
![image](https://user-images.githubusercontent.com/51334532/73400503-8c7c7000-42e9-11ea-9b27-99d4d3816581.png)

With horizontal pictures a big white space appears in the lower part of the div. I would either make the pictures always fill the div, make it resize automatically or center the picture vertically. Or avoid horiziontal pictures or whateverrr
![image](https://user-images.githubusercontent.com/51334532/73400965-7cb15b80-42ea-11ea-83e6-be37f63df51d.png)

Last but not least, the div containing the gallery looks slightly taller than the card on the left with the information. I find that quite disturbing, they should be the same height, oder?

When I select Parties the gallery just disappears. However, I would make only one gallery with everything, both parties and sports in it, it's simpler also for users.

**Comment by FraTheVet** [comment]
I feel like, depending on the order you're reading your notifications, you will - now or in the very future - kill me if I link to PR #12 again :joy:

Anyway, I digress
1. weird grid bug on sports section on mid-lg resolutions
2. big white space below images in carousel
3. height difference between card and carousel
4. parties carousel images missing

Most of it is taken care of in #12 :joy:
not sure if I already tested and pushed it or if it needs additional testing (twas 3AM) but 1. and 2. should be taken care of. 3. will need some additional work and possibly restructuring of the underlying components, it's on my todo list BTW. 4. was due to some missing images and therefore references and is now fixed. Also the carousel is the same, and you will be able to tell once merged by navigating through the pics. Tab names in the card component will simply trigger the carousel to go to a specific image

**Comment by lupusmochenus** [comment]
Alllright, you didn’t kill me for opening a million issues so we’re good pal!
Please let us know when legendary  #12 will be online, and I’ll come back opening more issues 😉


Da: Francesco Vettoretti<mailto:notifications@github.com>
Inviato: giovedì 30 gennaio 2020 00:27
A: SnowdaysIT/snowdays-front-end<mailto:snowdays-front-end@noreply.github.com>
Cc: lupusmochenus<mailto:filiberto97@live.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [SnowdaysIT/snowdays-front-end] Gallery for Sports and Parties, various problems (#16)


I feel like, depending on the order you're reading your notifications, you will - now or in the very future - kill me if I link to PR #12<https://github.com/SnowdaysIT/snowdays-front-end/pull/12> again 😂

Anyway, I digress

  1.  weird grid bug on sports section on mid-lg resolutions
  2.  big white space below images in carousel
  3.  height difference between card and carousel
  4.  parties carousel images missing

Most of it is taken care of in #12<https://github.com/SnowdaysIT/snowdays-front-end/pull/12> 😂
not sure if I already tested and pushed it or if it needs additional testing (twas 3AM) but 1. and 2. should be taken care of. 3. will need some additional work and possibly restructuring of the underlying components, it's on my todo list BTW. 4. was due to some missing images and therefore references and is now fixed. Also the carousel is the same, and you will be able to tell once merged by navigating through the pics. Tab names in the card component will simply trigger the carousel to go to a specific image

**Comment by FraTheVet** [comment]
@lupusmochenus wrote:
> Alllright, you didn’t kill me for opening a million issues so we’re good pal!
Please let us know when legendary  #12 will be online, and I’ll come back opening more issues 😉

Will close issues when it's online so you should be updated by email!

OT: I'd suggest not using GitHub mail reeply or being very careful with the body of the message as it included the original message, also posting email headers (anyone can see both your email and your email token, which are private). Deleting for that reason (and keeping message as initial quote of this message)

**Comment by FraTheVet** [comment]
Closing updates

#24 sends to production #12 with 1. 2. 3. and 4. fixed
