### ISSUE TITLE
Social buttons

### ISSUE THREAD

**Issue by filibert0** [SnowdaysIT/snowdays-front-end#20]
We haven't used twitter since 2016 and I don't think we will start using it again anytime soon. Please put a youtube icon+link instead of twitter!

It would be cool to have all logos in a snowdays blue colro and they become the social's original color when you hover on them!

**Comment by FraTheVet** [comment]
1. fair, in PR #12 I'll be touching them anyways since the current commits in there messed them up a bit

2. sounds like troubles with the Brand Asset Guides of the owners of the logos, not really sure about that (I.E. [Facebooks'](https://facebookbrand.com/wp-content/uploads/2019/12/Facebook-Brand-Assets-Guide-1.pdf), specifically page 6, "Don'ts")

**Comment by FraTheVet** [comment]
Closing updates

#24 sends to production #12 with 1. fixed and 2. left off (see previous coment)
